[build]
  command = "bun run build"
  publish = "dist"

[context.production]
  command = "bun run build"

[context.branch-deploy]
  command = "bun run build"

[context.deploy-preview]
  command = "bun run build"
